version: "3.8"

services:
  describe-it-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - describe-it-dev-network

networks:
  describe-it-dev-network:
    driver: bridge
