# Prometheus configuration for describe_it monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'describe-it-monitor'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the describe_it application
  - job_name: 'describe-it-app'
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_timeout: 10s
    honor_labels: true

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['node_exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis_exporter:9121']

  # Docker container metrics
  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']

  # Application health checks
  - job_name: 'describe-it-health'
    scrape_interval: 60s
    metrics_path: '/api/health'
    static_configs:
      - targets: ['app:3000']
    scrape_timeout: 30s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     headers:
#       Authorization: "Bearer <token>"

# Remote read configuration
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     headers:
#       Authorization: "Bearer <token>"