global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@describe-it.com'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        service: describe-it
      receiver: 'api-alerts'
      group_wait: 10s
      repeat_interval: 1h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://describe-it:3000/api/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'secret'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://describe-it:3000/api/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'secret'
    # Uncomment to enable email notifications
    # email_configs:
    #   - to: 'admin@describe-it.com'
    #     subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
    #       {{ end }}

  - name: 'api-alerts'
    webhook_configs:
      - url: 'http://describe-it:3000/api/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'secret'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']