apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: describe-it

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: describe-it
  version: v1.0.0