apiVersion: v1
kind: Secret
metadata:
  name: describe-it-secrets
  namespace: describe-it
  labels:
    app: describe-it
type: Opaque
stringData:
  # These should be base64 encoded in production
  # Use Kubernetes secrets management or external secret operators
  OPENAI_API_KEY: "your-openai-api-key-here"
  NEXT_PUBLIC_SUPABASE_URL: "your-supabase-url"
  SUPABASE_SERVICE_ROLE_KEY: "your-supabase-service-role-key"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "your-supabase-anon-key"
  REDIS_PASSWORD: "your-redis-password"
  DATABASE_URL: "your-database-url"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: describe-it
  labels:
    app: describe-it
    component: redis
type: Opaque
stringData:
  redis-password: "your-redis-password"