name: Pull Request Checks

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'src/components/**'
              - 'src/app/**'
              - 'src/styles/**'
              - 'public/**'
            backend:
              - 'src/app/api/**'
              - 'src/lib/**'
              - 'database/**'
            docs:
              - 'docs/**'
              - '*.md'
              - '.github/**'

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run component tests
        run: npm run test -- --reporter=verbose

      - name: Component visual regression tests
        run: npm run test:visual

  backend-tests:
    name: Backend API Tests
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm run test:api

  preview-deployment:
    name: Deploy Preview
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: true
          alias-domains: |
            describe-it-pr-${{ github.event.number }}.vercel.app

      - name: Run Lighthouse on Preview
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            ${{ steps.vercel-deploy.outputs.preview-url }}
            ${{ steps.vercel-deploy.outputs.preview-url }}/learn
            ${{ steps.vercel-deploy.outputs.preview-url }}/practice
          configPath: "./lighthouserc.js"
          temporaryPublicStorage: true
          uploadArtifacts: true

  accessibility-check:
    name: Accessibility Check
    runs-on: ubuntu-latest
    needs: preview-deployment
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install axe CLI
        run: npm install -g @axe-core/cli

      - name: Run accessibility tests
        run: |
          axe ${{ needs.preview-deployment.outputs.preview-url }} --exit

  security-review:
    name: Security Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build and check size
        run: npm run build

      - name: Check bundle size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: npm

  pr-summary:
    name: PR Summary
    runs-on: ubuntu-latest
    needs:
      [
        frontend-tests,
        backend-tests,
        preview-deployment,
        accessibility-check,
        security-review,
        size-check,
      ]
    if: always()
    steps:
      - name: Create PR Summary
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const jobs = [
              { name: 'Frontend Tests', status: '${{ needs.frontend-tests.result }}' },
              { name: 'Backend Tests', status: '${{ needs.backend-tests.result }}' },
              { name: 'Preview Deployment', status: '${{ needs.preview-deployment.result }}' },
              { name: 'Accessibility Check', status: '${{ needs.accessibility-check.result }}' },
              { name: 'Security Review', status: '${{ needs.security-review.result }}' },
              { name: 'Bundle Size Check', status: '${{ needs.size-check.result }}' }
            ];

            let summary = '## PR Check Summary\n\n';
            jobs.forEach(job => {
              const icon = job.status === 'success' ? '✅' : job.status === 'failure' ? '❌' : '⏭️';
              summary += `${icon} ${job.name}: ${job.status}\n`;
            });

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

  cleanup:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Delete Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--delete describe-it-pr-${{ github.event.number }}.vercel.app"
